
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 11 23:24:16 CST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSTANT = 8;
  public static final int AND = 4;
  public static final int LBRACKETS = 6;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RBRACKETS = 7;
  public static final int NOT = 5;
  public static final int OR = 3;
}

